version: '3.8'

services:
  # API Gateway (Development)
  gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile.dev
    container_name: ft_transcendence_gateway_dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ./services/gateway/src:/app/src
      - ./services/gateway/package.json:/app/package.json
      - ./services/gateway/tsconfig.json:/app/tsconfig.json
    depends_on:
      - auth-service
      - user-service
      - game-service
      - tournament-service
    networks:
      - ft_transcendence_network

  # Authentication Service (Development)
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    container_name: ft_transcendence_auth_dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      JWT_SECRET: dev-jwt-secret-key
    volumes:
      - ./services/auth-service/src:/app/src
      - ./services/auth-service/package.json:/app/package.json
      - ./services/auth-service/tsconfig.json:/app/tsconfig.json
    networks:
      - ft_transcendence_network

  # User Management Service (Development)
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile.dev
    container_name: ft_transcendence_user_dev
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      PORT: 3002
      JWT_SECRET: dev-jwt-secret-key
    volumes:
      - ./services/user-service/src:/app/src
      - ./services/user-service/package.json:/app/package.json
      - ./services/user-service/tsconfig.json:/app/tsconfig.json
      - ./services/user-service/data:/app/data
    networks:
      - ft_transcendence_network

  # Game Service (Development)
  game-service:
    build:
      context: ./services/game-service
      dockerfile: Dockerfile.dev
    container_name: ft_transcendence_game_dev
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: development
      PORT: 3003
    volumes:
      - ./services/game-service/src:/app/src
      - ./services/game-service/package.json:/app/package.json
      - ./services/game-service/tsconfig.json:/app/tsconfig.json
    networks:
      - ft_transcendence_network

  # Tournament Service (Development)
  tournament-service:
    build:
      context: ./services/tournament-service
      dockerfile: Dockerfile.dev
    container_name: ft_transcendence_tournament_dev
    ports:
      - "3004:3004"
    environment:
      NODE_ENV: development
      PORT: 3004
    volumes:
      - ./services/tournament-service/src:/app/src
      - ./services/tournament-service/package.json:/app/package.json
      - ./services/tournament-service/tsconfig.json:/app/tsconfig.json
    networks:
      - ft_transcendence_network

networks:
  ft_transcendence_network:
    driver: bridge
