version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - gateway-service
    networks:
      - pong-network
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  gateway-service:
    build:
      context: ./services/gateway-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - game-service
    networks:
      - pong-network
    volumes:
      - ./services/gateway-service:/gateway-service

  game-service:
    build:
      context: ./services/game-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
    networks:
      - pong-network
    volumes:
      - ./services/game-service:/game-service
      - /app/node_modules

networks:
  pong-network:

