version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    volumes:
      # Mount database file for persistence
      - ./data:/app/data
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - transcendence-network

  # Development service with hot reload
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=dev-secret-key
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      # Mount database file for persistence
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - transcendence-network
    profiles:
      - dev

networks:
  transcendence-network:
    driver: bridge

volumes:
  data:
    driver: local
  logs:
    driver: local
